
<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Broadcast Contact Editor</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminBroadcast') ?>">Broadcast</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminBroadcastContact') ?>">Contact</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
            </ol>
        </nav>
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST" class="row needs-validation main" novalidate>
                        <div class="col-md-6">
                            <?= $form->csrfField('noob') ?>
                            <?= $form->field('name'); ?>
                            <?= $form->field('phone'); ?>
                        </div>
                        <div class="col-md-6">
                            <?= $form->field('group', $groups) ?>
                            <div class="text-right">
                                <button class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>